### ISSUE TITLE
How to use this tool with Xbee S2 modules.

### ISSUE THREAD

**Issue by paulsonmathew21** [inguardians/zigbee_tools#1]
I wish to use the  tools to implement a project in which one Zigbee cordinator and an end device is present. I wish to introduce attack and also do so some verification using another zigbee xbee S2 device rather than using other hardware.

**Comment by haxorthematrix** [comment]
Communication to hardware with this project is accomplished through using the KillerBee framework.  At this time it does not appear that the KillerBee framework supports Xbee devices. Until supports is added under KillerBee, this will not be possible.

**Comment by joswr1ght** [comment]
Xbee devices, while great for prototyping endpoints, lack the necessary functionality to perform low-level attacks. Since they can't perform the necessary actions required for KillerBee attack tools, Xbee devices won't be integrated into the KillerBee project.

**Comment by haxorthematrix** [comment]
Josh, thanks for the clarification.
